name: Pull Request
body:
  - type: markdown
    attributes:
      value: |
        Provide a general summary of your changes in the Title above
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your changes in detail?
      placeholder: your changes!
      value: "your changes!"
    validations:
      required: true
      
  - type: checkboxes
    id: types-of-changes
    attributes:
      label: Types of changes
      description: What types of changes does your code introduce?
      options:
        - label: Bug fix (non-breaking change which fixes an issue)
        - label: New feature (non-breaking change which adds functionality)
        - label: Breaking change (fix or feature that would cause existing functionality to change)
          required: false
  
  - type: checkboxes
    id: code-guide
    attributes:
      label: Community guides
      description: What steps have you taken to make sure your code follow the community guides?
      options:
        - label: I have read the **CONTRIBUTING** document.
        - label: My code follows the code style of this project.
          required: true
  
  - type: checkboxes
    id: documentation
    attributes:
      label: Change to the documentation
      description: What types of changes does your code introduce?
      options:
        - label: My change requires a change to the documentation.
        - label: I have updated the documentation accordingly.
          required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this pull request, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
