+exclude_paths:
+- config/
+- db/
+- dist/
+- features/
+- **/node_modules/
+- script/
+- **/spec/
+- **/test/
+- **/tests/
+- Tests/
+- **/vendor/
+- **/*_test.go
+- **/*.d.ts
+- .travis.yml
+- parsedown.php
+- parsedown-extra.php
