plugins: 
  phpcodesniffer:
    enabled: true
    channel: beta
    config:
        standard: "PSR12"
    checks:
        file-lines:
            enabled: false
        Generic Files LineLength TooLong:
            enabled: false
exclude_patterns:
- "docs/"
- ".gitignore"
- ".editorconfig"
- ".gitattributes"
- ".composer.json"
