env:
  global:
    - CC_TEST_REPORTER_ID=a8e469f754fc364b94051183ece590ad3258d3e1619bf021233ad10645d5e0d9
language: php

dist: trusty
sudo: false

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

install:
  - composer install --prefer-source

rvm:
  - 2.2.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit
  - vendor/bin/phpunit vendor/benjaminhoegh/parsedown-extreme/test/CommonMarkTestWeak.php || true
  - '[ -z "$TRAVIS_TAG" ] || [ "$TRAVIS_TAG" == "$(php -r "require(\"vendor/autoload.php\"); echo parsedown-extreme::version;")" ]'
  # - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
