language: php

dist: trusty
sudo: false

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpunit
  - vendor/bin/phpunit vendor/BenjaminHoegh/ParsedownExtreme/test/CommonMarkTestWeak.php || true
  - '[ -z "$TRAVIS_TAG" ] || [ "$TRAVIS_TAG" == "$(php -r "require(\"vendor/autoload.php\"); echo ParsedownExtreme::version;")" ]'
