name: Bug Report
description: Help us improve by reporting bugs you've encountered
labels: [bug]
assignees:
  - BenjaminHoegh
body:
  - type: markdown
    attributes:
      value: |
        🐞 **Thank you for contributing to our project by reporting a bug!** 🐞
        Please provide as much detail as possible to help us efficiently resolve the issue.
        
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of what the bug is, including what you expected to happen and what actually happened.
      placeholder: "Explain the bug in detail. Include what you were doing when it occurred and any error messages you saw."
      value: ""
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Specify the PHP version you were using. This information helps us replicate the issue under similar conditions.
      placeholder: "e.g., 7.4.3"
    validations:
      required: true
      
  - type: input
    id: parsedown-version
    attributes:
      label: Parsedown Version
      description: Mention the version of Parsedown you're using. If possible, confirm if the issue persists with the latest version.
      placeholder: "e.g., 1.8.0"
    validations:
      required: true

  - type: input
    id: parsedown-extra-version
    attributes:
      label: Parsedown Extra Version
      description: If you're using Parsedown Extra, please specify the version. Leave blank if not applicable.
      placeholder: "Optional, e.g., 0.8.0"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct Agreement
      description: Confirm your agreement to adhere to our project's [Code of Conduct](https://github.com/BenjaminHoegh/ParsedownExtended/blob/main/.github/CODE_OF_CONDUCT.md). This helps maintain a respectful and constructive environment.
      options:
        - label: I agree to follow the project's Code of Conduct.
          required: true
