name: Bug Report
description: File a bug report
labels: [Bug]
assignees:
  - BenjaminHoegh
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: Also tell us, steps to reproduce the behavior
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us what should happen
      placeholder: Tell us what you expected too see
      value: "Tell us what you expected too see!"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/BenjaminHoegh/ParsedownExtended/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
