on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '**.php'
      - '**.yml'
      - '**.json'

jobs:
  lint_main:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PHP_BUILTIN: true
          VALIDATE_PHP_PHPCS: true
          VALIDATE_PHP_PSALM: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
